/*
GUESS THE NUMBER

The fun and easy project "Guess the Number" is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:

1. The system generates a random number from a given range, say 1 to 100.

2. The user is prompted to enter their given number in a displayed dialogue box.

3. The computer then tells if the entered number matches the guesses number or it is

higher/lower than the generated number.

4. The game continues under the user guessing the number. You can also incorporate further details as:

Limiting the number of attempts.

Adding more rounds.

Displaying score.

Giving points based on the number of attempts.
*/
import java.util.Random;
import java.util.Scanner;

public class GuessTheNumber {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        int lowerBound = 1;
        int upperBound = 100;
        int totalAttempts = 0;
        int totalScore = 0;
        int rounds = 3;  // Number of rounds

        System.out.println("Welcome to Guess the Number Game!");
        System.out.println("I have selected a random number between " + lowerBound + " and " + upperBound + ". Can you guess it?");

        for (int round = 1; round <= rounds; round++) {
            int number = random.nextInt(upperBound - lowerBound + 1) + lowerBound;
            int attempts = 0;
            boolean hasGuessedCorrectly = false;

            while (!hasGuessedCorrectly && attempts < 5) {  // Allowing a maximum of 5 attempts per round
                System.out.print("Round " + round + " - Attempt #" + (attempts + 1) + ": Enter your guess: ");
                int guess = scanner.nextInt();
                attempts++;

                if (guess < lowerBound || guess > upperBound) {
                    System.out.println("Please guess a number between " + lowerBound + " and " + upperBound + ".");
                } else if (guess < number) {
                    System.out.println("Too low! Try again.");
                } else if (guess > number) {
                    System.out.println("Too high! Try again.");
                } else {
                    hasGuessedCorrectly = true;
                    int roundScore = 6 - attempts;  // Giving points based on the number of attempts
                    totalScore += roundScore;
                    System.out.println("Congratulations! You've guessed the number in " + attempts + " attempts. You scored " + roundScore + " points in this round.");
                }
            }

            totalAttempts += attempts;

            if (round < rounds) {
                System.out.println("Round " + round + " ended. Next round starts!");
            }
        }

        System.out.println("Game Over! You took " + totalAttempts + " attempts in total and scored " + totalScore + " points.");
        scanner.close();
    }
}

